[package]
name = "nix-shell-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.4"
dirs = "6.0.0"
clap = { version = "4.5.38", features = ["derive", "color"] }
unicode-segmentation = "1.12.0"
